TREINOS = {
    "Full Body 3x": {
        "Dia 1 (Full Body)": [
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Supino Reto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Remada Curvada", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Desenvolvimento", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Shoulder-Press.gif"},
            {"ex": "Rosca Scott", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Prancha", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2025/07/body-saw-plank.gif"}
        ],
        "Dia 2 (Descanso)": [{"ex": "Day Off"}],
        "Dia 3 (Full Body)": [
            {"ex": "Leg Press", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Supino Inclinado", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Puxada Aberta", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Elevação Lateral", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Rosca Alternada", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"},
            {"ex": "Tríceps Francês", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Seated-Dumbbell-Triceps-Extension.gif"}
        ],
        "Dia 4 (Descanso)": [{"ex": "Day Off"}],
        "Dia 5 (Full Body)": [
            {"ex": "Stiff", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Remada Baixa", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif"},
            {"ex": "Elevação Frontal", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Alternating-Dumbbell-Front-Raise.gif"},
            {"ex": "Rosca Direta (Barra)", "sets": "3x10",
             "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif"},
            {"ex": "Tríceps Polia", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"}
        ]
    },
    "Full Body 4x": {
        "Dia 1 (Full Body)": [
            {"ex": "Agachamento Smith", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2024/10/smith-machine-squat.gif"},
            {"ex": "Supino Inclinado", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Remada Curvada", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Desenvolvimento Halteres", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Rosca Scott", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Tríceps Polia", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"}
        ],
        "Dia 2 (Full Body)": [
            {"ex": "Leg Press", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Agachamento Pêndulo", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/10/Pendulum-Squat.gif"},
            {"ex": "Elevação Panturrilha", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif"},
            {"ex": "Supino Reto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Elevação Frontal", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Alternating-Dumbbell-Front-Raise.gif"},
            {"ex": "Rosca Alternada", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"},
            {"ex": "Tríceps Francês", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Seated-Dumbbell-Triceps-Extension.gif"}
        ],
        "Dia 3 (Descanso)": [{"ex": "Day Off"}],
        "Dia 4 (Full Body)": [
            {"ex": "Stiff", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Cadeira Flexora", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Cadeira Extensora", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Face Pull", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif"},
            {"ex": "Crucifixo Inverso", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Rear-Delt-Machine-Flys.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Tríceps Polia", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"}
        ],
        "Dia 5 (Full Body)": [
            {"ex": "Abdutor", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"},
            {"ex": "Remada Unilateral", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif"},
            {"ex": "Desenvolvimento Halteres", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Rosca Direta (barra)", "sets": "3x10",
             "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif"},
            {"ex": "Tríceps Polia", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"}
        ]
    },
    "Upper/Lower 2x": {
        "Dia 1 (Upper)": [
            {"ex": "Pulldown Unilateral", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Cable-One-Arm-Lat-Pulldown.gif"},
            {"ex": "T-Bar Row ", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/t-bar-rows.gif"},
            {"ex": "Puxada Triângulo", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/V-bar-Lat-Pulldown.gif"},
            {"ex": "Supino Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Voador", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pec-Deck-Fly.gif"},
            {"ex": "Elevação Lateral", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Tríceps Polia", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Rosca Scott", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"}
        ],
        "Dia 2 (Lower)": [
            {"ex": "Mesa Flexora", "sets": "4x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Agachamento Pêndulo", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/10/Pendulum-Squat.gif"},
            {"ex": "Cadeira Extensora", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Stiff", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Abdutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"}
        ],
        "Dia 3 (Descanso)": [{"ex": "Day Off"}],
        "Dia 4 (Upper)": [
            {"ex": "Puxada Aberta", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Remada Unilateral", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif"},
            {"ex": "Supino Reto", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Desenvolvimento", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Shoulder-Press.gif"},
            {"ex": "Rosca Scott", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Tríceps Dips", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/04/parallel-bar-dip.gif"},
            {"ex": "Lombar Banco", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Weighted-Back-Extension.gif"}
        ],
        "Dia 5 (Lower)": [
            {"ex": "Flexora Sentado", "sets": "4x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/08/Seated-Leg-Curl.gif"},
            {"ex": "Agachamento", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Leg Press", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Elevação Pélvica", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif"},
            {"ex": "Abdutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"}
        ]
    },
    "PPL 2x": {
        "Dia 1 Push(Empurrar)": [
            {"ex": "Supino Reto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Crucifixo Reto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif"},
            {"ex": "Tríceps Polia", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Skull Crusher", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Triceps-Extension.gif"},
            {"ex": "Desenvolvimento", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Shoulder-Press.gif"},
            {"ex": "Elevação Lateral", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"}
        ],
        "Dia 2 Pull(Puxar)": [
            {"ex": "Puxada Aberta", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Remada Baixa", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif"},
            {"ex": "Remada Curvada", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Rosca Alternada", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"},
            {"ex": "Rosca Scott", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Rosca Martelo", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif"}
        ],
        "Dia 3 Legs(Pernas)": [
            {"ex": "Agachamento Livre", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Stiff", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Cadeira Extensora", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Elevação Pélvica", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif"},
            {"ex": "Agachamento Búlgaro", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2023/03/Bulgarian-Jump-Squat.gif"}
        ],
        "Dia 4 Push(Empurrar)": [
            {"ex": "Supino Inclinado", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Crossover Alto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/High-Cable-Crossover.gif"},
            {"ex": "Tríceps Overhead", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/Cable-Rope-Overhead-Triceps-Extension.gif"},
            {"ex": "Tríceps Francês", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Seated-Dumbbell-Triceps-Extension.gif"},
            {"ex": "Crucifixo Inverso", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Rear-Delt-Machine-Flys.gif"},
            {"ex": "Face Pull", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif"}
        ],
        "Dia 5 Pull(Puxar)": [
            {"ex": "Puxada Aberta", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Barra Fixa", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif"},
            {"ex": "Remada Unilateral", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif"},
            {"ex": "Rosca Alternada", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"},
            {"ex": "Rosca Martelo", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif"},
            {"ex": "Rosca Direta (Barra)", "sets": "3x12",
             "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif"}
        ],
        "Dia 6 Legs(Pernas)": [
            {"ex": "Abdutor", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"},
            {"ex": "Cadeira Flexora", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Leg Press", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Agachamento Sumô", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/dumbbell-sumo-squat.gif"},
            {"ex": "Elevação Panturrilha", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif"}
        ]
    },
    "Upper/Lower 2x + Full Body": {
        "Dia 1 (Upper)": [
            {"ex": "Pulldown Unilateral", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Cable-One-Arm-Lat-Pulldown.gif"},
            {"ex": "T-Bar Row ", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/t-bar-rows.gif"},
            {"ex": "Puxada Triângulo", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/V-bar-Lat-Pulldown.gif"},
            {"ex": "Supino Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Voador", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pec-Deck-Fly.gif"},
            {"ex": "Elevação Lateral", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Tríceps Polia", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Rosca Scott", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"}
        ],
        "Dia 2 (Lower)": [
            {"ex": "Mesa Flexora", "sets": "4x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Agachamento Pêndulo", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/10/Pendulum-Squat.gif"},
            {"ex": "Cadeira Extensora", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Stiff", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Abdutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"}
        ],
        "Dia 3 (Upper)": [
            {"ex": "Puxada Aberta", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Remada Unilateral", "sets": "4x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif"},
            {"ex": "Supino Reto", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Desenvolvimento", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Shoulder-Press.gif"},
            {"ex": "Rosca Scott", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Tríceps Dips", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/04/parallel-bar-dip.gif"},
            {"ex": "Lombar Banco", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Weighted-Back-Extension.gif"}
        ],
        "Dia 4 (Lower)": [
            {"ex": "Flexora Sentado", "sets": "4x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/08/Seated-Leg-Curl.gif"},
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Leg Press", "sets": "3x15",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Elevação Pélvica", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif"},
            {"ex": "Abdutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "4x20",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"}
        ],
        "Dia 5 (Full Body)": [
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Supino Reto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Remada Curvada", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Desenvolvimento", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Shoulder-Press.gif"},
            {"ex": "Rosca Scott", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Prancha", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2025/07/body-saw-plank.gif"}
        ]
    },
    "Bro Split": {
        "Dia 1 (Peito)": [
            {"ex": "Supino Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Supino Reto", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Crossover Alto", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/High-Cable-Crossover.gif"},
            {"ex": "Voador", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pec-Deck-Fly.gif"},
            {"ex": "Dips", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/04/parallel-bar-dip.gif"}
        ],
        "Dia 2 (Costas)": [
            {"ex": "Barra Fixa", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif"},
            {"ex": "Puxada Triângulo", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/V-bar-Lat-Pulldown.gif"},
            {"ex": "Remada Baixa", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif"},
            {"ex": "Remada Curvada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Remada Unilateral", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif"},
            {"ex": "Pullover", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Pullover.gif"}
        ],
        "Dia 3 (Ombro)": [
            {"ex": "Elevação Lateral", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Elevação Frontal", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Alternating-Dumbbell-Front-Raise.gif"},
            {"ex": "Desenvolvimento Halteres", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Crucifixo Inverso", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Rear-Delt-Machine-Flys.gif"},
            {"ex": "Face Pull", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif"}
        ],
        "Dia 4 (Pernas)": [
            {"ex": "Abdutor", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Adutor", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"},
            {"ex": "Cadeira Flexora", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Cadeira Flexora", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Leg Press", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Agachamento Búlgaro", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2023/03/Bulgarian-Jump-Squat.gif"}
        ],
        "Dia 5 (Bíceps/Tríceps)": [
            {"ex": "Rosca Alternada", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"},
            {"ex": "Rosca Scott", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/dumbbell-scot-curl.gif"},
            {"ex": "Rosca Martelo", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif"},
            {"ex": "Tríceps Polia", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Tríceps Overhead", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/Cable-Rope-Overhead-Triceps-Extension.gif"},
            {"ex": "Tríceps Francês", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Seated-Dumbbell-Triceps-Extension.gif"}
        ]
    },
    "Lower Focus (LULUL)": {
        "Dia 1 (Lower)": [
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Leg Press", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Cadeira Extensora", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Afundo", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2025/09/pendulum-lunge.gif"},
            {"ex": "Elevação Panturrilha", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif"},
            {"ex": "Prancha", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2025/07/body-saw-plank.gif"}
        ],
        "Dia 2 (Upper)": [
            {"ex": "Supino reto", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Puxada Triângulo", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/V-bar-Lat-Pulldown.gif"},
            {"ex": "Desenvolvimento Halteres", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Remada Curvada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Tríceps Skull Crusher", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Triceps-Extension.gif"},
            {"ex": "Rosca Alternada", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"}
        ],
        "Dia 3 (Lower)": [
            {"ex": "Levantamento Terra", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif"},
            {"ex": "Mesa Flexora", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Elevação Pélvica", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif"},
            {"ex": "Agachamento Búlgaro", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2023/03/Bulgarian-Jump-Squat.gif"},
            {"ex": "Elevação Panturrilha", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif"},
            {"ex": "Abdominal", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/05/Weighted-Crunch.gif"}
        ],
        "Dia 4 (Upper)": [
            {"ex": "Supino Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Puxada Aberta", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Elevação Lateral", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Remada Baixa", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif"},
            {"ex": "Tríceps Polia", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Rosca Alternada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"}
        ],
        "Dia 5 (Lower)": [
            {"ex": "Agachamento Goblet", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2025/07/Heel-Elevated-Goblet-Squat.gif"},
            {"ex": "Agachamento Hack", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Sled-Hack-Squat.gif"},
            {"ex": "Stiff", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Passada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2023/10/Static-Lunge.gif"},
            {"ex": "Leg Press", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"}
        ]
    },
    "Arnold Split": {
        "Dia 1 (Peito + Costas)": [
            {"ex": "Supino Reto", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Barra Fixa", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif"},
            {"ex": "Supino Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Remada Curvada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Puxada Aberta", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Pullover", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Pullover.gif"}
        ],
        "Dia 2 (Ombro + Braços)": [
            {"ex": "Desenvolvimento Halteres", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Elevação Lateral", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Elevação Frontal", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Alternating-Dumbbell-Front-Raise.gif"},
            {"ex": "Encolhimento", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/Dumbbell-Shrug.gif"},
            {"ex": "Rosca Direta + Tríceps Skull Crusher",
                "sets": "2x12", "video": "https://fitnessprogramer.com/wp-content/uploads/2022/04/Double-Arm-Dumbbell-Curl.gif"},
            {"ex": "Rosca Alternada + Tríceps Polia", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/11/One-arm-triceps-pushdown.gif"},
            {"ex": "Rosca Concentrada + Dips", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Bench-Dips.gif"}
        ],
        "Dia 3 (Pernas)": [
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Leg Press", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Extensora", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Mesa Flexora", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Stiff", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Elevação Panturrilha", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif"}
        ],
        "Dia 4 (Peito + Costas)": [
            {"ex": "Supino Reto", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Barra Fixa", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif"},
            {"ex": "Supino Inclinado", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Remada Curvada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif"},
            {"ex": "Crucifixo Inclinado", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif"},
            {"ex": "Puxada Aberta", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Pullover", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Pullover.gif"}
        ],
        "Dia 5 (Ombro + Braços)": [
            {"ex": "Desenvolvimento Halteres", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Elevação Lateral", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Elevação Frontal", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Alternating-Dumbbell-Front-Raise.gif"},
            {"ex": "Encolhimento", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/Dumbbell-Shrug.gif"},
            {"ex": "Rosca Direta + Tríceps Skull Crusher",
                "sets": "2x12", "video": ""},
            {"ex": "Rosca Alternada + Tríceps Polia", "sets": "3x30s", "video": ""},
            {"ex": "Rosca Concentrada + Dips", "sets": "3x30s", "video": ""}
        ],
        "Dia 6 (Pernas)": [
            {"ex": "Agachamento Livre", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Leg Press", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Extensora", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Mesa Flexora", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif"},
            {"ex": "Stiff", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Elevação Panturrilha", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif"}
        ]
    },
    "UL PPL": {
        "Dia 1 (Upper)": [
            {"ex": "Rosca Direta Barra", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif"},
            {"ex": "Rosca Preacher", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Z-Bar-Preacher-Curl.gif"},
            {"ex": "Tríceps Polia", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Tríceps Francês", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Seated-Dumbbell-Triceps-Extension.gif"},
            {"ex": "Crossover Alto", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/High-Cable-Crossover.gif"},
            {"ex": "Supino Inclinado", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif"},
            {"ex": "Barra Fixa", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif"},
            {"ex": "Puxada Aberta", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"}
        ],
        "Dia 2 (Lower + Ombro)": [
            {"ex": "Abdutor", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HiP-ABDUCTION-MACHINE.gif"},
            {"ex": "Cadeira Flexora", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/08/Seated-Leg-Curl.gif"},
            {"ex": "Agachamento Pêndulo", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/10/Pendulum-Squat.gif"},
            {"ex": "Leg Press", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif"},
            {"ex": "Stiff", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2022/01/Stiff-Leg-Deadlift.gif"},
            {"ex": "Crucifixo Inverso", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Rear-Delt-Machine-Flys.gif"},
            {"ex": "Face Pull", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif"},
            {"ex": "Elevação Lateral", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"}
        ],
        "Dia 3 (Peito + Tríceps)": [
            {"ex": "Supino Reto", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif"},
            {"ex": "Crucifixo Reto", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif"},
            {"ex": "Power Press", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2024/12/Barbell-JM-Press.gif"},
            {"ex": "Crossover Baixo", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Low-Cable-Crossover.gif"},
            {"ex": "Tríceps Polia", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif"},
            {"ex": "Tríceps Skull Crusher", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Triceps-Extension.gif"},
            {"ex": "Tríceps Overhead", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/04/Cable-Rope-Overhead-Triceps-Extension.gif"}
        ],
        "Dia 4 (Costas + Bíceps)": [
            {"ex": "Puxada Aberta", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif"},
            {"ex": "Remada Baixa", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif"},
            {"ex": "Remada Unilateral", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif"},
            {"ex": "Pullover Polia", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Rope-Straight-Arm-Pulldown.gif"},
            {"ex": "Rosca Alternada", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif"},
            {"ex": "Rosca Martelo", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif"},
            {"ex": "Rosca Direta Barra", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif"}
        ],
        "Dia 5 (Lower + Ombro)": [
            {"ex": "Adutor", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif"},
            {"ex": "Cadeira Extensora", "sets": "3x10",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif"},
            {"ex": "Agachamento Búlgaro", "sets": "3x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2023/03/Bulgarian-Jump-Squat.gif"},
            {"ex": "Agachamento Livre", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif"},
            {"ex": "Desenvolvimento Halteres", "sets": "2x12",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif"},
            {"ex": "Elevação Lateral", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif"},
            {"ex": "Elevação Elevação Frontal", "sets": "3x30s",
                "video": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Alternating-Dumbbell-Front-Raise.gif"}
        ]
    }
}
